### ISSUE TITLE
Widget CircleProgress utilisation

### ISSUE THREAD

**Issue by EricChanussot** [noodom/jeedom_widgets#1]
Bonjour Noodom,
Faut-il obligatoirement installer le plugin Pimp My Jeedom pour utiliser votre Widget circleProgress ?
Notamment pour l’ajout du fichier circle-progress.js ?
Bien cordialement

**Comment by noodom** [comment]
Salut nerixs,

Non, bien sûr ,le plugin Pimp n'est pas obligatoire, c'est juste une facilité d'installation que j'utilise d'ailleurs pour mes développements.
J'ai d'ailleurs prévu d'ajouter dans la documentation la méthode pour ajouter manuellement le widget.

Mais tu peux déjà faire l'installation comme toute installation classique d'un widget tiers à partir du menu "Outils->Widgets" (voir le paragraphe "Widgets personnalisés" de la documentation Jeedom à l'aide du bouton "?").

Bonne soirée.

**Comment by EricChanussot** [comment]
J’ai ajouté le code du fichier cmd.info.numeric.circleProgress.html depuis le menu "Outils->Widgets->Code", mais comment ajouter le fichier circle-progress.js ?
Bien cordialement

**Comment by noodom** [comment]
Il faut ajouter le fichier .js au même endroit que le fichier généré du widget créé, dans un répertoire du même nom que le nom du widget.

Tu auras alors : 
- /html/data/customTemplates/dashboard/cmd.info.numeric.circleProgress.html
- /html/data/customTemplates/dashboard/cmd.info.numeric.circleProgress/circle-progress.js

Attention de bien vérifier que le path correspond à celui précisé dans le code du widget (si t n'as pas changé le nom du widget, c'est ok) : 
` $.include(['data/customTemplates/dashboard/cmd.info.numeric.circleProgress/circle-progress.js'],`

**Comment by EricChanussot** [comment]
Salut Moodom,
Un grand merci pour les explications.
J’ai associé ton widget à ma sonde de température extérieur, les températures négatives ou positives sont bien gérées.
J’ai vu que tu avais posté un exemple du plus belle effet sur https://community.jeedom.com/t/tuto-noodom-nouveau-widget-circleprogress/52595/8, avec changement de couleurs selon la température.
Pourrais-tu me guider ou me donner un exemple pour avoir le même effet ?
Je suppose que le style de base est le N°2 ?
Félicitation pour le travail effectué et merci pour le partage.

**Comment by noodom** [comment]
La couleur en fonction de la valeur se fait par défaut si les paramètres couleurValeur pour le cercle et couleurTexte pour le texte ne sont pas renseignés.

Si ils sont renseignés, alors la couleur reste fixe avec la valeur du paramètre.

Tu peux tester la variation de couleurs en mettant aucun paramètre.

**Comment by EricChanussot** [comment]
Je ne sais pas si c’est un bug, j’ai retiré les paramètres optionnels couleurValeur et couleurTexte j’ai le texte en bleu turquoise et le cercle en rose foncé.
Ils devraient être de la même couleur non ?
En option j’ai :
style : 2
min : -20
max : 50
taille : 150px
uniteChamp : °
tailleFonteTexte : 18px
largeurCercle : 12px
couleurFondCercle: transparent

![Capture1](https://user-images.githubusercontent.com/51137494/107671848-970b6c80-6c94-11eb-8f6e-bfbca34c0aa5.JPG)

**Comment by noodom** [comment]
Non, ce n'est pas un bug.
Le style 2 prédéfinit les couleurs du cercle (à 'hsl(320,80%,60%)') et du texte (à 'hsl(180,80%,47%)')

Donc ils restent fixes.

Si tu veux reprendre les paramètres du style 2 avec des couleurs changeantes, il faut le paramétrage suivant (champs des couleurs à vide pour écraser les valeurs prédéfinies par le style) : 

![image](https://user-images.githubusercontent.com/24904155/107673027-db4b3c80-6c95-11eb-9ab7-b9412a04a6c1.png)

**Comment by EricChanussot** [comment]
OK, merci pour l’explication.
J’essaie de comprendre votre code, avec mon petit niveau en développement :).
Si je comprends bien seul le style 8 est compatible nativement avec le changement de couleurs.

**Comment by noodom** [comment]
en utilisant les style, oui. Sinon il faut saisir son propre paramétrage ou comme je le précisais passer les 2 paramètres de couleur à vide.

**Comment by EricChanussot** [comment]
Bonjour,
Quelques ajouts pourraient être sympa sur ton widget si l'envie et ton temps te le permets.
Afficher la durée depuis le dernier changement.
Flèche de tendance paramétrable.
Dans l'idée du code ci-dessous:

[cmd.info.numeric.tendance.html.txt](https://github.com/noodom/jeedom_widgets/files/5970512/cmd.info.numeric.tendance.html.txt)

.txt a retirer ;)

Bien cordialement

**Comment by noodom** [comment]
Ajouté dans la (longue) TODO :)
