### ISSUE TITLE
Chart type Polar

### ISSUE THREAD

**Issue by bbreton09** [noodom/jeedom_widgets#3]
Bonjour, pas une issue les widgets fonctionne vraiment très bien. Juste une question. : 

Pensez vous qu'il soit possible d'ajouter la rose des vents (wind rose) polar dans les types de chart ?
https://www.highcharts.com/samples/highcharts/demo/polar-wind-rose?codepen
Merci d'avance pour votre retour.

**Comment by noodom** [comment]
Bonjour,

Par manque de temps, je n'ai hélas pas prévu d'ajouter la rose des vents.
A voir par la suite si je trouve le temps d'y jeter un oeil.
